// <auto-generated />
using System;
using LPG_Tsumitate_Kanri2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LPG_Tsumitate_Kanri2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422080429_AddIsOnLeave")]
    partial class AddIsOnLeave
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.CollectionRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("RecordId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SessionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("CollectionRecords");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.CollectionSession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SavingsTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SessionDate")
                        .HasColumnType("date");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("SavingsTypeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("CollectionSessions");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.ContributionAmountRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ConditionEmploymentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ConditionMaxYearsOfService")
                        .HasColumnType("int");

                    b.Property<string>("ConditionPositionCategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SavingsTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("RuleId");

                    b.HasIndex("SavingsTypeId");

                    b.ToTable("ContributionAmountRules");

                    b.HasData(
                        new
                        {
                            RuleId = 1,
                            Amount = 1000,
                            Priority = 1,
                            SavingsTypeId = 1,
                            ValidFrom = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RuleId = 2,
                            Amount = 500,
                            ConditionEmploymentType = "パート",
                            Priority = 1,
                            SavingsTypeId = 2,
                            ValidFrom = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RuleId = 3,
                            Amount = 500,
                            ConditionMaxYearsOfService = 3,
                            Priority = 2,
                            SavingsTypeId = 2,
                            ValidFrom = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RuleId = 4,
                            Amount = 2000,
                            ConditionPositionCategory = "役職者",
                            Priority = 3,
                            SavingsTypeId = 2,
                            ValidFrom = new DateOnly(2026, 1, 1)
                        },
                        new
                        {
                            RuleId = 5,
                            Amount = 1000,
                            ConditionPositionCategory = "一般職",
                            Priority = 4,
                            SavingsTypeId = 2,
                            ValidFrom = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnLeave")
                        .HasColumnType("bit");

                    b.Property<string>("PositionCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("EmployeeId");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.LedgerEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SavingsTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceSessionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("EntryId");

                    b.HasIndex("SavingsTypeId");

                    b.HasIndex("SourceSessionId");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("ReceiptId");

                    b.HasIndex("EntryId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.SavingsType", b =>
                {
                    b.Property<int>("SavingsTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavingsTypeId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SavingsTypeId");

                    b.ToTable("SavingsTypes");

                    b.HasData(
                        new
                        {
                            SavingsTypeId = 1,
                            DisplayOrder = 1,
                            Name = "通常積立"
                        },
                        new
                        {
                            SavingsTypeId = 2,
                            DisplayOrder = 2,
                            Name = "還暦積立"
                        });
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.CollectionRecord", b =>
                {
                    b.HasOne("LPG_Tsumitate_Kanri2.Models.Entities.Employee", "Employee")
                        .WithMany("CollectionRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LPG_Tsumitate_Kanri2.Models.Entities.CollectionSession", "Session")
                        .WithMany("CollectionRecords")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.CollectionSession", b =>
                {
                    b.HasOne("LPG_Tsumitate_Kanri2.Models.Entities.SavingsType", "SavingsType")
                        .WithMany("CollectionSessions")
                        .HasForeignKey("SavingsTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SavingsType");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.ContributionAmountRule", b =>
                {
                    b.HasOne("LPG_Tsumitate_Kanri2.Models.Entities.SavingsType", "SavingsType")
                        .WithMany("ContributionAmountRules")
                        .HasForeignKey("SavingsTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SavingsType");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.LedgerEntry", b =>
                {
                    b.HasOne("LPG_Tsumitate_Kanri2.Models.Entities.SavingsType", "SavingsType")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("SavingsTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LPG_Tsumitate_Kanri2.Models.Entities.CollectionSession", "SourceSession")
                        .WithMany()
                        .HasForeignKey("SourceSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SavingsType");

                    b.Navigation("SourceSession");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.Receipt", b =>
                {
                    b.HasOne("LPG_Tsumitate_Kanri2.Models.Entities.LedgerEntry", "Entry")
                        .WithMany("Receipts")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.CollectionSession", b =>
                {
                    b.Navigation("CollectionRecords");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.Employee", b =>
                {
                    b.Navigation("CollectionRecords");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.LedgerEntry", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("LPG_Tsumitate_Kanri2.Models.Entities.SavingsType", b =>
                {
                    b.Navigation("CollectionSessions");

                    b.Navigation("ContributionAmountRules");

                    b.Navigation("LedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
