using System.ComponentModel.DataAnnotations;

namespace LPG_Tsumitate_Kanri2.Models.Entities;

public class LedgerEntry
{
    public int EntryId { get; set; }

    [Required]
    [Display(Name = "積立種別")]
    public int SavingsTypeId { get; set; }

    [Required]
    [Display(Name = "収支発生日")]
    public DateOnly TransactionDate { get; set; }

    [Required]
    [MaxLength(10)]
    [Display(Name = "区分")]
    public string EntryType { get; set; } = string.Empty; // 入金 / 出金

    [Required]
    [MaxLength(200)]
    [Display(Name = "内容")]
    public string Description { get; set; } = string.Empty;

    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "金額は1以上の整数を入力してください")]
    [Display(Name = "金額（円）")]
    public int Amount { get; set; }

    [Display(Name = "残高")]
    public int BalanceAfter { get; set; }

    public bool IsAutoGenerated { get; set; }

    public int? SourceSessionId { get; set; }

    [MaxLength(500)]
    [Display(Name = "備考")]
    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public SavingsType SavingsType { get; set; } = null!;
    public CollectionSession? SourceSession { get; set; }
    public ICollection<Receipt> Receipts { get; set; } = new List<Receipt>();
}
