using Microsoft.EntityFrameworkCore;
using LPG_Tsumitate_Kanri2.Models.Entities;
using LPG_Tsumitate_Kanri2.Services;

namespace LPG_Tsumitate_Kanri2.Data;

public static class DataSeeder
{
    public static async Task SeedAsync(AppDbContext db, ContributionCalculator calculator)
    {
        // 既にデータがある場合はスキップ
        if (await db.Employees.AnyAsync()) return;

        // ── 社員 ──────────────────────────────────────────────────────────────
        var employees = new List<Employee>
        {
            new() { EmployeeNo = "E001", FullName = "山田 太郎",   HireDate = new DateOnly(2018, 4, 1),  EmploymentType = "正社員", PositionCategory = "役職者", BirthDate = new DateOnly(1970, 5, 15) },
            new() { EmployeeNo = "E002", FullName = "佐藤 花子",   HireDate = new DateOnly(2020, 10, 1), EmploymentType = "正社員", PositionCategory = "一般職", BirthDate = new DateOnly(1990, 3, 22) },
            new() { EmployeeNo = "E003", FullName = "鈴木 一郎",   HireDate = new DateOnly(2025, 1, 6),  EmploymentType = "正社員", PositionCategory = "一般職", BirthDate = new DateOnly(1998, 8, 10) },
            new() { EmployeeNo = "E004", FullName = "田中 美咲",   HireDate = new DateOnly(2019, 7, 1),  EmploymentType = "パート",  PositionCategory = "一般職", BirthDate = new DateOnly(1985, 11, 3) },
            new() { EmployeeNo = "E005", FullName = "伊藤 健二",   HireDate = new DateOnly(2016, 4, 1),  EmploymentType = "正社員", PositionCategory = "役職者", BirthDate = new DateOnly(1966, 4, 28) },
            new() { EmployeeNo = "E006", FullName = "渡辺 さくら", HireDate = new DateOnly(2022, 6, 1),  EmploymentType = "パート",  PositionCategory = "一般職", BirthDate = new DateOnly(2000, 1, 17) },
        };
        db.Employees.AddRange(employees);
        await db.SaveChangesAsync();

        // ── 徴収セッション × CollectionRecord（過去3か月分 × 2種別）────────────
        var months = new[]
        {
            (Year: 2026, Month: 1),
            (Year: 2026, Month: 2),
            (Year: 2026, Month: 3),
        };

        var savingsTypeIds = new[] { 1, 2 }; // 1=通常積立, 2=還暦積立
        int runningBalance1 = 0; // 通常積立残高
        int runningBalance2 = 0; // 還暦積立残高

        foreach (var (year, month) in months)
        {
            var asOf = new DateOnly(year, month, 1);

            foreach (var stId in savingsTypeIds)
            {
                var rules = await db.ContributionAmountRules
                    .Where(r => r.SavingsTypeId == stId
                        && r.ValidFrom <= asOf
                        && (r.ValidTo == null || r.ValidTo >= asOf))
                    .OrderBy(r => r.Priority)
                    .ToListAsync();

                var session = new CollectionSession
                {
                    SavingsTypeId = stId,
                    Year = year,
                    Month = month,
                    SessionDate = new DateOnly(year, month, 20),
                    IsCompleted = true,
                    CreatedAt = new DateTime(year, month, 1)
                };
                db.CollectionSessions.Add(session);
                await db.SaveChangesAsync();

                // 通常積立は全員、還暦積立は全員対象（除外なし）
                var records = employees.Select(emp => new CollectionRecord
                {
                    SessionId = session.SessionId,
                    EmployeeId = emp.EmployeeId,
                    ExpectedAmount = calculator.Calculate(emp, rules, asOf),
                    IsCollected = true,
                    IsExcluded = false,
                    CollectedAt = new DateTime(year, month, 20)
                }).ToList();

                // 通常積立のみ：1人を不参加として除外（テスト用）
                if (stId == 1 && records.Count > 0)
                {
                    records[^1].IsCollected = false;
                    records[^1].IsExcluded = true;
                    records[^1].CollectedAt = null;
                }

                db.CollectionRecords.AddRange(records);
                await db.SaveChangesAsync();

                // 徴収合計を収支帳簿に自動入金として追加
                var savingsTypeName = stId == 1 ? "通常積立" : "還暦積立";
                var totalAmount = records.Where(r => r.IsCollected && !r.IsExcluded).Sum(r => r.ExpectedAmount);

                ref var balance = ref (stId == 1 ? ref runningBalance1 : ref runningBalance2);
                balance += totalAmount;

                var incomeEntry = new LedgerEntry
                {
                    SavingsTypeId = stId,
                    TransactionDate = new DateOnly(year, month, 20),
                    EntryType = "入金",
                    Description = $"{year}年{month}月分 {savingsTypeName} 徴収分",
                    Amount = totalAmount,
                    BalanceAfter = balance,
                    IsAutoGenerated = true,
                    SourceSessionId = session.SessionId,
                    CreatedAt = new DateTime(year, month, 20)
                };
                db.LedgerEntries.Add(incomeEntry);
                await db.SaveChangesAsync();
            }
        }

        // ── 手動支出（2月・3月に出金）────────────────────────────────────────
        // 2月：通常積立から食事会費支出
        runningBalance1 -= 15000;
        db.LedgerEntries.Add(new LedgerEntry
        {
            SavingsTypeId = 1,
            TransactionDate = new DateOnly(2026, 2, 20),
            EntryType = "出金",
            Description = "2月懇親会 食事代",
            Amount = 15000,
            BalanceAfter = runningBalance1,
            IsAutoGenerated = false,
            CreatedAt = new DateTime(2026, 2, 20)
        });

        // 3月：通常積立から誕生日プレゼント
        runningBalance1 -= 3000;
        db.LedgerEntries.Add(new LedgerEntry
        {
            SavingsTypeId = 1,
            TransactionDate = new DateOnly(2026, 3, 10),
            EntryType = "出金",
            Description = "佐藤さん誕生日プレゼント",
            Amount = 3000,
            BalanceAfter = runningBalance1,
            IsAutoGenerated = false,
            CreatedAt = new DateTime(2026, 3, 10)
        });

        await db.SaveChangesAsync();

        // ── 今月（4月）の進行中セッション──────────────────────────────────────
        // 通常積立（未完了・徴収チェック用）
        var apr = new DateOnly(2026, 4, 1);
        var rulesNormal = await db.ContributionAmountRules
            .Where(r => r.SavingsTypeId == 1 && r.ValidFrom <= apr && (r.ValidTo == null || r.ValidTo >= apr))
            .OrderBy(r => r.Priority).ToListAsync();

        var aprNormalSession = new CollectionSession
        {
            SavingsTypeId = 1,
            Year = 2026,
            Month = 4,
            SessionDate = new DateOnly(2026, 4, 25),
            IsCompleted = false,
            CreatedAt = DateTime.Now
        };
        db.CollectionSessions.Add(aprNormalSession);
        await db.SaveChangesAsync();

        var aprNormalRecords = employees.Select((emp, i) => new CollectionRecord
        {
            SessionId = aprNormalSession.SessionId,
            EmployeeId = emp.EmployeeId,
            ExpectedAmount = calculator.Calculate(emp, rulesNormal, apr),
            IsCollected = i < 3, // 最初の3人は徴収済み
            IsExcluded = false,
            CollectedAt = i < 3 ? DateTime.Now : null
        }).ToList();
        db.CollectionRecords.AddRange(aprNormalRecords);

        // 還暦積立（未完了）
        var rulesKanreki = await db.ContributionAmountRules
            .Where(r => r.SavingsTypeId == 2 && r.ValidFrom <= apr && (r.ValidTo == null || r.ValidTo >= apr))
            .OrderBy(r => r.Priority).ToListAsync();

        var aprKanrekiSession = new CollectionSession
        {
            SavingsTypeId = 2,
            Year = 2026,
            Month = 4,
            SessionDate = new DateOnly(2026, 4, 25),
            IsCompleted = false,
            CreatedAt = DateTime.Now
        };
        db.CollectionSessions.Add(aprKanrekiSession);
        await db.SaveChangesAsync();

        var aprKanrekiRecords = employees.Select((emp, i) => new CollectionRecord
        {
            SessionId = aprKanrekiSession.SessionId,
            EmployeeId = emp.EmployeeId,
            ExpectedAmount = calculator.Calculate(emp, rulesKanreki, apr),
            IsCollected = i < 2, // 最初の2人のみ徴収済み
            IsExcluded = false,
            CollectedAt = i < 2 ? DateTime.Now : null
        }).ToList();
        db.CollectionRecords.AddRange(aprKanrekiRecords);

        await db.SaveChangesAsync();
    }
}
