using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LPG_Tsumitate_Kanri2.Data;
using LPG_Tsumitate_Kanri2.Models.Entities;
using LPG_Tsumitate_Kanri2.Models.ViewModels;
using LPG_Tsumitate_Kanri2.Services;

namespace LPG_Tsumitate_Kanri2.Controllers;

public class LedgerController : Controller
{
    private readonly AppDbContext _db;
    private readonly LedgerService _ledgerService;

    public LedgerController(AppDbContext db, LedgerService ledgerService)
    {
        _db = db;
        _ledgerService = ledgerService;
    }

    public async Task<IActionResult> Index(int? savingsTypeId, int? year, int? month)
    {
        var query = _db.LedgerEntries.Include(e => e.SavingsType).AsQueryable();

        if (savingsTypeId.HasValue) query = query.Where(e => e.SavingsTypeId == savingsTypeId.Value);
        if (year.HasValue) query = query.Where(e => e.TransactionDate.Year == year.Value);
        if (month.HasValue) query = query.Where(e => e.TransactionDate.Month == month.Value);

        var entries = await query
            .OrderByDescending(e => e.TransactionDate)
            .ThenByDescending(e => e.EntryId)
            .ToListAsync();

        ViewBag.SavingsTypes = await _db.SavingsTypes.OrderBy(s => s.DisplayOrder).ToListAsync();
        ViewBag.FilterSavingsTypeId = savingsTypeId;
        ViewBag.FilterYear = year;
        ViewBag.FilterMonth = month;
        return View(entries);
    }

    public async Task<IActionResult> Create()
    {
        var vm = new LedgerFormViewModel
        {
            SavingsTypes = await _db.SavingsTypes.OrderBy(s => s.DisplayOrder).ToListAsync()
        };
        return View(vm);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(LedgerFormViewModel model)
    {
        if (!ModelState.IsValid)
        {
            model.SavingsTypes = await _db.SavingsTypes.OrderBy(s => s.DisplayOrder).ToListAsync();
            return View(model);
        }

        var entry = new LedgerEntry
        {
            SavingsTypeId = model.SavingsTypeId,
            TransactionDate = model.TransactionDate,
            EntryType = model.EntryType,
            Description = model.Description,
            Amount = model.Amount,
            Notes = model.Notes,
            IsAutoGenerated = false,
            CreatedAt = DateTime.Now
        };
        await _ledgerService.SetBalanceAsync(entry);
        _db.LedgerEntries.Add(entry);
        await _db.SaveChangesAsync();

        // 後続レコードの残高を再計算
        await _ledgerService.RecalculateFromAsync(entry.SavingsTypeId, entry.TransactionDate, entry.EntryId + 1);

        return RedirectToAction(nameof(Index), new { savingsTypeId = entry.SavingsTypeId });
    }

    public async Task<IActionResult> Edit(int id)
    {
        var entry = await _db.LedgerEntries.Include(e => e.SavingsType).FirstOrDefaultAsync(e => e.EntryId == id);
        if (entry == null) return NotFound();
        if (entry.IsAutoGenerated) return BadRequest("自動生成されたレコードは編集できません。");

        var vm = new LedgerFormViewModel
        {
            EntryId = entry.EntryId,
            SavingsTypeId = entry.SavingsTypeId,
            TransactionDate = entry.TransactionDate,
            EntryType = entry.EntryType,
            Description = entry.Description,
            Amount = entry.Amount,
            Notes = entry.Notes,
            SavingsTypes = await _db.SavingsTypes.OrderBy(s => s.DisplayOrder).ToListAsync()
        };
        return View(vm);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, LedgerFormViewModel model)
    {
        if (!ModelState.IsValid)
        {
            model.SavingsTypes = await _db.SavingsTypes.OrderBy(s => s.DisplayOrder).ToListAsync();
            return View(model);
        }

        var entry = await _db.LedgerEntries.FindAsync(id);
        if (entry == null) return NotFound();
        if (entry.IsAutoGenerated) return BadRequest();

        var oldDate = entry.TransactionDate;
        entry.TransactionDate = model.TransactionDate;
        entry.EntryType = model.EntryType;
        entry.Description = model.Description;
        entry.Amount = model.Amount;
        entry.Notes = model.Notes;

        await _ledgerService.SetBalanceAsync(entry);
        await _db.SaveChangesAsync();

        var recalcFrom = oldDate < entry.TransactionDate ? oldDate : entry.TransactionDate;
        await _ledgerService.RecalculateFromAsync(entry.SavingsTypeId, recalcFrom, 0);

        return RedirectToAction(nameof(Index), new { savingsTypeId = entry.SavingsTypeId });
    }

    public async Task<IActionResult> Details(int id)
    {
        var entry = await _db.LedgerEntries
            .Include(e => e.SavingsType)
            .Include(e => e.Receipts)
            .Include(e => e.SourceSession)
            .FirstOrDefaultAsync(e => e.EntryId == id);

        if (entry == null) return NotFound();
        return View(entry);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var entry = await _db.LedgerEntries.FindAsync(id);
        if (entry == null) return NotFound();
        if (entry.IsAutoGenerated) return BadRequest("自動生成されたレコードは削除できません。");

        var savingsTypeId = entry.SavingsTypeId;
        var deleteDate = entry.TransactionDate;
        var deleteEntryId = entry.EntryId;

        _db.LedgerEntries.Remove(entry);
        await _db.SaveChangesAsync();

        await _ledgerService.RecalculateFromAsync(savingsTypeId, deleteDate, deleteEntryId);

        return RedirectToAction(nameof(Index), new { savingsTypeId });
    }
}
